{% set name = "stamina" %}
{% set version = "23.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/stamina-{{ version }}.tar.gz
  sha256: 48f1b3c39ea7e03775fdc0653f9f6ad183b401c84e0eeada12ff18accc712a61

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.8
    - hatchling
    - hatch-vcs
    - hatch-fancy-pypi-readme >=22.8.0
    - pip
  run:
    - python >=3.8
    - tenacity
    # including this for all python to stay noarch: python
    - typing-extensions

test:
  imports:
    - stamina
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hynek/stamina
  summary: Production-grade retries made easy.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://stamina.hynek.me/en/stable/
  dev_url: https://github.com/hynek/stamina

extra:
  recipe-maintainers:
    - xylar
