{% set name = "stamina" %}
{% set version = "24.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/stamina-{{ version }}.tar.gz
  sha256: 1d763c98962ca11f1729c357422926a750a138e803e7beb9f9d6c99d33d9997d

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - hatch-fancy-pypi-readme >=22.8.0
    - pip
  run:
    - python >={{ python_min }}
    - tenacity
    # including this for all python to stay noarch: python
    - typing-extensions

test:
  imports:
    - stamina
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/hynek/stamina
  summary: Production-grade retries made easy.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://stamina.hynek.me/en/stable/
  dev_url: https://github.com/hynek/stamina

extra:
  recipe-maintainers:
    - xylar
